`-*- mode: org; mode: visual-line;  -*-`
#+STARTUP: indent

* `nanomator` [[http://travis-ci.org/cassiel/nanomator][https://secure.travis-ci.org/cassiel/nanomator.png]] [[https://www.versioneye.com/user/projects/53d2a43b851c56dc68000231][https://www.versioneye.com/user/projects/53d2a43b851c56dc68000231/badge.svg]]

* Introduction

A Clojure library for simple timeline-based automation, useful for animation systems.

An automation state maps named *channels* to time-varying values. Each channel can be populated with automation segments, each of which has a start time, duration and target value for the channel's value.

=nanomator= doesn't have a particular notion of time: it just uses integer counters which can be milliseconds (for realtime animation), frames (for rendering), or anything else.

By default, channel values are floats, but it's possible to attach interpolation functions to allow automation over arbitrary data values (for example, vectors of floats for RGB colour mixing).

* Usage

In =project.clj=:

#+BEGIN_SRC clojure
  [eu.cassiel/nanomator "0.1.0-SNAPSHOT"]
#+END_SRC

In the code:


#+BEGIN_SRC clojure
  (:require [eu.cassiel [nanomator :as nn]])
#+END_SRC

Create a new automation state with

#+BEGIN_SRC clojure
  (nn/???)
#+END_SRC

* Documentation

The source documentation is [[https://cassiel.github.io/nanomator][here]].

* License

Copyright © 2014 Nick Rothwell.

Distributed under the Eclipse Public License either version 1.0 or (at your option) any later version.
